//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vm167Box.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vm167Box.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel for the Velleman VM167 USB GPIO interface card..
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog1.
        /// </summary>
        internal static string Analog1 {
            get {
                return ResourceManager.GetString("Analog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog2.
        /// </summary>
        internal static string Analog2 {
            get {
                return ResourceManager.GetString("Analog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog3.
        /// </summary>
        internal static string Analog3 {
            get {
                return ResourceManager.GetString("Analog3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog4.
        /// </summary>
        internal static string Analog4 {
            get {
                return ResourceManager.GetString("Analog4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog5.
        /// </summary>
        internal static string Analog5 {
            get {
                return ResourceManager.GetString("Analog5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog in calibration.
        /// </summary>
        internal static string AnalogInCalibration {
            get {
                return ResourceManager.GetString("AnalogInCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM167 Box.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card in use.
        /// </summary>
        internal static string CardInUse {
            get {
                return ResourceManager.GetString("CardInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open the driver, check connections and try again.
        /// </summary>
        internal static string DriverProblem {
            get {
                return ResourceManager.GetString("DriverProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string GeneratorTitle {
            get {
                return ResourceManager.GetString("GeneratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No VM167 card found.
        /// </summary>
        internal static string NoCardFound {
            get {
                return ResourceManager.GetString("NoCardFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string PanelTitle {
            get {
                return ResourceManager.GetString("PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point1.
        /// </summary>
        internal static string Point1 {
            get {
                return ResourceManager.GetString("Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point2.
        /// </summary>
        internal static string Point2 {
            get {
                return ResourceManager.GetString("Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwm1.
        /// </summary>
        internal static string Pwm1 {
            get {
                return ResourceManager.GetString("Pwm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwm2.
        /// </summary>
        internal static string Pwm2 {
            get {
                return ResourceManager.GetString("Pwm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM out calibration.
        /// </summary>
        internal static string PwmOutCalibration {
            get {
                return ResourceManager.GetString("PwmOutCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string ScopeTitle {
            get {
                return ResourceManager.GetString("ScopeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle dark/light theme.
        /// </summary>
        internal static string ThemeToggle {
            get {
                return ResourceManager.GetString("ThemeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value1.
        /// </summary>
        internal static string Value1 {
            get {
                return ResourceManager.GetString("Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value2.
        /// </summary>
        internal static string Value2 {
            get {
                return ResourceManager.GetString("Value2", resourceCulture);
            }
        }
    }
}
