//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vm167Box.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vm167Box.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel for the Velleman VM167 USB GPIO interface card..
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog1.
        /// </summary>
        internal static string Analog1 {
            get {
                return ResourceManager.GetString("Analog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog2.
        /// </summary>
        internal static string Analog2 {
            get {
                return ResourceManager.GetString("Analog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog3.
        /// </summary>
        internal static string Analog3 {
            get {
                return ResourceManager.GetString("Analog3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog4.
        /// </summary>
        internal static string Analog4 {
            get {
                return ResourceManager.GetString("Analog4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog5.
        /// </summary>
        internal static string Analog5 {
            get {
                return ResourceManager.GetString("Analog5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog In.
        /// </summary>
        internal static string AnalogIn {
            get {
                return ResourceManager.GetString("AnalogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM167 Box.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card 0 connected.
        /// </summary>
        internal static string Card0Connected {
            get {
                return ResourceManager.GetString("Card0Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card 1 connected.
        /// </summary>
        internal static string Card1Connected {
            get {
                return ResourceManager.GetString("Card1Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card in use.
        /// </summary>
        internal static string CardInUse {
            get {
                return ResourceManager.GetString("CardInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Digital.
        /// </summary>
        internal static string ClearAllDigital {
            get {
                return ResourceManager.GetString("ClearAllDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string DigitalIn {
            get {
                return ResourceManager.GetString("DigitalIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital In/Out.
        /// </summary>
        internal static string DigitalInOut {
            get {
                return ResourceManager.GetString("DigitalInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string DigitalOut {
            get {
                return ResourceManager.GetString("DigitalOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open the driver, check connections and try again.
        /// </summary>
        internal static string DriverProblem {
            get {
                return ResourceManager.GetString("DriverProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Cycle (%).
        /// </summary>
        internal static string DutyCycle {
            get {
                return ResourceManager.GetString("DutyCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator PWM1.
        /// </summary>
        internal static string GeneratorPwm1 {
            get {
                return ResourceManager.GetString("GeneratorPwm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator PWM2.
        /// </summary>
        internal static string GeneratorPwm2 {
            get {
                return ResourceManager.GetString("GeneratorPwm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string GeneratorTitle {
            get {
                return ResourceManager.GetString("GeneratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Signal.
        /// </summary>
        internal static string MaxSignal {
            get {
                return ResourceManager.GetString("MaxSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value.
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Signal.
        /// </summary>
        internal static string MinSignal {
            get {
                return ResourceManager.GetString("MinSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value.
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No VM167 card found.
        /// </summary>
        internal static string NoCardFound {
            get {
                return ResourceManager.GetString("NoCardFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OffWave {
            get {
                return ResourceManager.GetString("OffWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string PanelTitle {
            get {
                return ResourceManager.GetString("PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period (s).
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwm1.
        /// </summary>
        internal static string Pwm1 {
            get {
                return ResourceManager.GetString("Pwm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwm2.
        /// </summary>
        internal static string Pwm2 {
            get {
                return ResourceManager.GetString("Pwm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwm Out.
        /// </summary>
        internal static string PwmOut {
            get {
                return ResourceManager.GetString("PwmOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string ScopeTitle {
            get {
                return ResourceManager.GetString("ScopeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Card:.
        /// </summary>
        internal static string SelectCard {
            get {
                return ResourceManager.GetString("SelectCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All Digital.
        /// </summary>
        internal static string SetAllDigital {
            get {
                return ResourceManager.GetString("SetAllDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine.
        /// </summary>
        internal static string SineWave {
            get {
                return ResourceManager.GetString("SineWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string SquareWave {
            get {
                return ResourceManager.GetString("SquareWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle dark/light theme.
        /// </summary>
        internal static string ThemeToggle {
            get {
                return ResourceManager.GetString("ThemeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        internal static string TriangleWave {
            get {
                return ResourceManager.GetString("TriangleWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Value.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
